Modified script for parser; Added script for AST generation

diff --git a/bin/parser b/bin/parser
--- a/bin/parser
+++ b/bin/parser
@@ -2,7 +2,7 @@
 
 # Taking the path to Golang source file
 if [[ $# -ne 1 ]]; then
-    echo "Enter only the path to the source file as argument" >&2
+    echo "Enter only the path to the source file as argument with extension .go" >&2
     exit 2
 fi
 
@@ -10,8 +10,33 @@ export MILESTONE=3
 
 path_to_root=$( dirname $( dirname $( realpath $0) ) )
 abs_path_to_parser="${path_to_root}/src/Milestone${MILESTONE}/parser.py"
+abs_path_to_gen_ast="${path_to_root}/src/Milestone${MILESTONE}/gen_ast.py"
 abs_path_to_file=$(realpath $1)
-
+abs_path_to_output=$(echo $abs_path_to_file | sed 's/.go$/.output/')
+abs_path_to_dot=$(echo $abs_path_to_file | sed 's/.go$/.dot/')
+abs_path_to_pdf=$(echo $abs_path_to_file | sed 's/.go$/.pdf/')
 export PATH_TO_ROOT=$path_to_root
 
 python3 $abs_path_to_parser $abs_path_to_file
+if [ $? != 0 ];
+then
+    echo "Compilation Failed!"
+    exit 1
+fi
+echo "Compilation Successful!"
+python3 $abs_path_to_gen_ast $abs_path_to_output
+if [ $? != 0 ];
+then
+    echo "AST Generation failed!"
+    exit 1
+fi
+echo "AST Generated Successfully!"
+dot -Tpdf $abs_path_to_dot -o $abs_path_to_pdf
+if [ $? != 0 ];
+then
+    echo "PDF Generation failed!"
+    echo "If dot is not installed, install dot using 'sudo apt install graphviz'"
+    exit 1
+fi
+echo "PDF Generated Successfully!"
+xdg-open $abs_path_to_pdf
